query workspaceList($userId: Int!) {
  user(id: $userId) {
    id
    workspaces {
      id
      name
      slug
      events {
        id
        name
        slug
        icon
        color
        createdAt
        updatedAt
      }
    }
  }
}
