fragment day on Day {
  id
  title
  startsAt

  agendas {
    id
    title

    startSlot
    endSlot
  }

  duties {
    id
    title

    startSlot
    endSlot

    assignees {
      id
      displayName

      user {
        photo
      }
    }
  }
}
