query event($eventId: Int!, $owned: Boolean) {
  event(id: $eventId) {
    id
    name
    slug
    icon
    color
    createdAt
    updatedAt

    today(owned: $owned) {
      ...day
    }

    me {
      ...staff
    }
  }
}
