fragment day on Day {
  id
  title
  startsAt

  roles {
    id
    type
    title
  }

  agendas {
    id
    slot
    title
  }

  duties {
    id
    slot
    title

    manager {
      id
      title
      type
    }

    assignees {
      id
      displayName

      user {
        id
        photo
        displayName
      }
    }
  }
}
